function:
  name: fn_set_responsible_party_v2
  schema: public
configuration:
  custom_name: set_responsible_party
permissions:
  - role: clinic_user
    permission:
      filter:
        _exists:
          _table:
            name: clinic_user_effective_capabilities_v
            schema: public
          _where:
            _and:
              - clinic_id:
                  _eq: X-Hasura-Clinic-Id
              - user_id:
                  _eq: X-Hasura-User-Id
              - _or:
                  - capability_key:
                      _eq: patient_manage
                  - capability_key:
                      _eq: billing.manage
                  - capability_key:
                      _eq: system_admin
