flyway.url=jdbc:postgresql://postgres:5432/tessdental
flyway.user=tess
flyway.password=tess_password_change_me

flyway.schemas=public
flyway.table=schema_history

flyway.locations=filesystem:/flyway/sql
flyway.validateOnMigrate=true
flyway.outOfOrder=false
flyway.baselineOnMigrate=false

# Keep things strict
flyway.cleanDisabled=true
