table:
  name: app_user_v
  schema: public
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - id
        - email
        - first_name
        - last_name
        - is_active
        - created_at
        - created_by
        - updated_at
        - updated_by
        - current_clinic_id
      filter: {}
