table:
  name: clinic_user_role
  schema: public
insert_permissions:
  - role: clinic_user
    permission:
      check:
        _exists:
          _table:
            name: clinic_user_effective_capabilities_v
            schema: public
          _where:
            _and:
              - clinic_id:
                  _eq: X-Hasura-Clinic-Id
              - user_id:
                  _eq: X-Hasura-User-Id
              - _or:
                  - capability_key:
                      _eq: users_manage
                  - capability_key:
                      _eq: system_admin
      columns:
        - clinic_user_id
        - role_id
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - clinic_user_id
        - role_id
      filter: {}
delete_permissions:
  - role: clinic_user
    permission:
      filter:
        _exists:
          _table:
            name: clinic_user_effective_capabilities_v
            schema: public
          _where:
            _and:
              - clinic_id:
                  _eq: X-Hasura-Clinic-Id
              - user_id:
                  _eq: X-Hasura-User-Id
              - _or:
                  - capability_key:
                      _eq: users_manage
                  - capability_key:
                      _eq: system_admin
