table:
  name: app_user_v
  schema: public
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - id
        - email
        - first_name
        - last_name
        - is_active
        - created_at
        - updated_at
      filter: {}
insert_permissions: []
update_permissions: []
delete_permissions: []
