table:
  name: clinic
  schema: public
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - id
        - name
        - timezone
        - phone
        - fax
        - website
        - email
        - address_street
        - address_unit
        - address_city
        - address_province
        - address_postal
        - billing_number
        - is_active
        - created_at
        - updated_at
      filter:
        id:
          _eq: X-Hasura-Clinic-Id
insert_permissions: []
update_permissions:
  - role: clinic_user
    permission:
      filter:
        id:
          _eq: X-Hasura-Clinic-Id
      columns:
        - name
        - timezone
        - phone
        - fax
        - website
        - email
        - address_street
        - address_unit
        - address_city
        - address_province
        - address_postal
        - billing_number
      check:
        id:
          _eq: X-Hasura-Clinic-Id
delete_permissions: []
