table:
  name: patient
  schema: public
object_relationships:
  - name: patient_financial
    using:
      manual_configuration:
        column_mapping:
          person_id: patient_person_id
        insertion_order: null
        remote_table:
          name: patient_financial
          schema: public
  - name: person
    using:
      foreign_key_constraint_on: person_id
array_relationships:
  - name: patient_referral
    using:
      foreign_key_constraint_on:
        column: patient_person_id
        table:
          name: patient_referral
          schema: public
insert_permissions:
  - role: clinic_user
    permission:
      check:
        _and:
          - person:
              clinic_id:
                _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
      columns:
        - person_id
        - chart_no
        - status
        - family_doctor_name
        - family_doctor_phone
        - imaging_id
        - is_active
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - person_id
        - chart_no
        - status
        - family_doctor_name
        - family_doctor_phone
        - imaging_id
        - is_active
        - created_at
        - created_by
        - updated_at
        - updated_by
      filter:
        person:
          clinic_id:
            _eq: X-Hasura-Clinic-Id
update_permissions:
  - role: clinic_user
    permission:
      columns:
        - chart_no
        - status
        - family_doctor_name
        - family_doctor_phone
        - imaging_id
        - is_active
      filter:
        person:
          clinic_id:
            _eq: X-Hasura-Clinic-Id
      check:
        _and:
          - person:
              clinic_id:
                _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
delete_permissions:
  - role: clinic_user
    permission:
      filter:
        _and:
          - person:
              clinic_id:
                _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
