table:
  name: clinic
  schema: public
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - id
        - name
        - timezone
        - phone
        - fax
        - website
        - email
        - address_street
        - address_unit
        - address_city
        - address_province
        - address_postal
        - billing_number
        - is_active
        - created_at
        - updated_at
      filter:
        id:
          _eq: X-Hasura-Clinic-Id
update_permissions:
  - role: clinic_user
    permission:
      columns:
        - name
        - timezone
        - phone
        - fax
        - website
        - email
        - address_street
        - address_unit
        - address_city
        - address_province
        - address_postal
        - billing_number
      filter:
        id:
          _eq: X-Hasura-Clinic-Id
      check:
        _and:
          - id:
              _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: clinic_manage
                      - capability_key:
                          _eq: system_admin
