table:
  name: patient_referral
  schema: public
object_relationships:
  - name: patient
    using:
      foreign_key_constraint_on: patient_person_id
  - name: referral_contact_person
    using:
      foreign_key_constraint_on: referral_contact_person_id
  - name: referral_kind_enum
    using:
      manual_configuration:
        column_mapping:
          referral_kind: value
        insertion_order: null
        remote_table:
          name: referral_kind_enum
          schema: public
  - name: referral_source
    using:
      foreign_key_constraint_on: referral_source_id
insert_permissions:
  - role: clinic_user
    permission:
      check:
        _and:
          - patient:
              person:
                clinic_id:
                  _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
      columns:
        - patient_person_id
        - referral_kind
        - referral_source_id
        - referral_contact_person_id
        - referral_other_text
        - is_active
select_permissions:
  - role: clinic_user
    permission:
      columns:
        - patient_person_id
        - referral_kind
        - referral_source_id
        - referral_contact_person_id
        - referral_other_text
        - is_active
        - created_at
        - created_by
        - updated_at
        - updated_by
      filter:
        patient:
          person:
            clinic_id:
              _eq: X-Hasura-Clinic-Id
update_permissions:
  - role: clinic_user
    permission:
      columns:
        - referral_kind
        - referral_source_id
        - referral_contact_person_id
        - referral_other_text
        - is_active
      filter:
        patient:
          person:
            clinic_id:
              _eq: X-Hasura-Clinic-Id
      check:
        _and:
          - patient:
              person:
                clinic_id:
                  _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
delete_permissions:
  - role: clinic_user
    permission:
      filter:
        _and:
          - patient:
              person:
                clinic_id:
                  _eq: X-Hasura-Clinic-Id
          - _exists:
              _table:
                name: clinic_user_effective_capabilities_v
                schema: public
              _where:
                _and:
                  - clinic_id:
                      _eq: X-Hasura-Clinic-Id
                  - user_id:
                      _eq: X-Hasura-User-Id
                  - _or:
                      - capability_key:
                          _eq: patient_manage
                      - capability_key:
                          _eq: system_admin
