- "!include audit_event.yaml"
- "!include public_address.yaml"
- "!include public_app_user.yaml"
- "!include public_app_user_v.yaml"
- "!include public_capability.yaml"
- "!include public_clinic.yaml"
- "!include public_clinic_hours.yaml"
- "!include public_clinic_hours_v.yaml"
- "!include public_clinic_user.yaml"
- "!include public_clinic_user_effective_capabilities_v.yaml"
- "!include public_clinic_user_role.yaml"
- "!include public_clinic_user_v.yaml"
- "!include public_clinic_user_with_profile_v.yaml"
- "!include public_clinic_v.yaml"
- "!include public_contact_kind_enum.yaml"
- "!include public_family_group_v.yaml"
- "!include public_family_members_v.yaml"
- "!include public_field_config.yaml"
- "!include public_gender_enum.yaml"
- "!include public_household_relationship_enum.yaml"
- "!include public_insurance_subscriber.yaml"
- "!include public_operatory.yaml"
- "!include public_operatory_v.yaml"
- "!include public_patient.yaml"
- "!include public_patient_field_config.yaml"
- "!include public_patient_financial.yaml"
- "!include public_patient_profile_v.yaml"
- "!include public_patient_referral.yaml"
- "!include public_patient_status_enum.yaml"
- "!include public_person.yaml"
- "!include public_person_contact_point.yaml"
- "!include public_person_with_responsible_party_v.yaml"
- "!include public_referral_kind_enum.yaml"
- "!include public_referral_source.yaml"
- "!include public_role.yaml"
- "!include public_role_capability.yaml"
- "!include public_role_v.yaml"
- "!include public_search_household_heads_result.yaml"
- "!include public_user_profile.yaml"
- "!include public_user_provider_identifier.yaml"
- "!include public_user_provider_identifier_v.yaml"
- "!include public_imaging_asset.yaml"
- "!include public_imaging_study.yaml"
- "!include public_imaging_mount_template.yaml"
- "!include public_imaging_mount.yaml"
- "!include public_imaging_mount_slot.yaml"
- "!include public_imaging_clinic_mount_settings.yaml"
- "!include public_imaging_clinic_mount_template.yaml"
